language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

script:
  - ant -f clangFormatWrapper/clangFormatWrapper.xml build
  - java -jar clangFormatWrapper.jar clangFormatWrapper --verbose --init
  - java -jar clangFormatWrapper.jar clangFormatWrapper --verbose