language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ant; fi

script:
  - ant -f formattingHelper/build.xml build
  - java -jar formattingHelper.jar formattingHelper --verbose --init
  - java -jar formattingHelper.jar formattingHelper --verbose