install:
  - cinst ant
  - refreshenv

build_script:
  - ant -f clangFormatWrapper/clangFormatWrapper.xml build

test_script:
  - java -jar clangFormatWrapper.jar clangFormatWrapper --verbose --init
  - java -jar clangFormatWrapper.jar clangFormatWrapper --verbose