install:
  - cinst ant
  - refreshenv

build_script:
  - ant -f formattingHelper/build.xml build

test_script:
  - java -jar formattingHelper.jar formattingHelper --verbose --init
  - java -jar formattingHelper.jar formattingHelper --verbose