install:
  - cinst ant

before_build:
  - set PATH=%PATH%;"C:\Program Files\Java\jdk1.8.0"

build_script:
  - ant -f clangFormatWrapper/clangFormatWrapper.xml build

test_script:
  - java -jar clangFormatWrapper.jar clangFormatWrapper --verbose --init
  - java -jar clangFormatWrapper.jar clangFormatWrapper --verbose